// the block table, against the python oracle.
//
// `test/fixtures/survey-expected.txt` is `jobs/survey.py`'s own stdout over
// `test/fixtures/home` (limits log and transcripts both), regenerated by
// `scripts/refresh-oracle.sh`. every block's measured points, tokens and list
// cost has to come out the same here, because those three numbers are what the
// whole page divides.
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { blocks, limitsLogPath, monotonic, readSamples } from './samples'
import { splitBlock } from './split'
import { projectsRoot, scan } from './transcripts'

const FIXTURE_HOME = join(import.meta.dirname, '..', 'test', 'fixtures', 'home')
const SURVEY = join(import.meta.dirname, '..', 'test', 'fixtures', 'survey-expected.txt')

interface OracleRow {
  label: string
  points: number
  mtok: number
  cost: number
}

/** the fixed-width rows of survey.py's first table: `10 Sep 13:20   97    8.1   10.4 …` */
function oracleRows(): OracleRow[] {
  const out: OracleRow[] = []
  for (const line of readFileSync(SURVEY, 'utf8').split('\n')) {
    const match = /^(\d\d \w\w\w \d\d:\d\d)\s+(-?\d+)\s+(\d+\.\d)\s+(\d+\.\d)\s/.exec(line)
    if (match) out.push({ label: match[1]!, points: Number(match[2]), mtok: Number(match[3]), cost: Number(match[4]) })
  }
  return out
}

const label = new Intl.DateTimeFormat('en-US', {
  timeZone: 'Europe/Prague',
  day: '2-digit',
  month: 'numeric',
  hour: '2-digit',
  minute: '2-digit',
  hour12: false,
})
const MONTHS = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

/** `10 Sep 13:20`, the same block label survey.py prints */
function blockLabel(start: number): string {
  const parts = label.formatToParts(new Date(start * 1000))
  const get = (type: string) => parts.find((p) => p.type === type)!.value
  return `${get('day')} ${MONTHS[Number(get('month')) - 1]} ${get('hour')}:${get('minute')}`
}

describe('the block table, against jobs/survey.py', () => {
  it('measures the same points, tokens and list cost per block', async () => {
    const expected = oracleRows()
    expect(expected.length).toBeGreaterThan(4)

    const samples = readSamples(limitsLogPath(FIXTURE_HOME))
    const all = blocks(samples)
    const { records, sessions } = await scan(0, 9_999_999_999, projectsRoot(FIXTURE_HOME))
    expect(all).toHaveLength(expected.length)

    all.forEach((block, index) => {
      const row = expected[index]!
      const kept = monotonic(block.samples)
      const from = kept[0]!.t
      const to = kept.at(-1)!.t
      const delta = kept.at(-1)!.pct - kept[0]!.pct
      const split = splitBlock(records, sessions, { from, to, delta, blockStart: block.start })
      const tokens = split.sessions.reduce((sum, s) => sum + s.tokens, 0)

      expect(blockLabel(block.start), `block ${index}`).toBe(row.label)
      expect(delta, `${row.label} points`).toBe(row.points)
      // survey.py prints one decimal, so agreement is to half of one
      expect(tokens / 1e6, `${row.label} Mtok`).toBeCloseTo(row.mtok, 1)
      expect(split.totalCost, `${row.label} list cost`).toBeCloseTo(row.cost, 1)
    })
  })

  it('splits every block into shares that add up', async () => {
    const samples = readSamples(limitsLogPath(FIXTURE_HOME))
    const { records, sessions } = await scan(0, 9_999_999_999, projectsRoot(FIXTURE_HOME))
    for (const block of blocks(samples)) {
      const kept = monotonic(block.samples)
      const split = splitBlock(records, sessions, {
        from: kept[0]!.t,
        to: kept.at(-1)!.t,
        delta: kept.at(-1)!.pct - kept[0]!.pct,
        blockStart: block.start,
      })
      if (!split.sessions.length) continue
      expect(split.sessions.reduce((sum, s) => sum + s.share, 0)).toBeCloseTo(1, 9)
      const points = split.sessions.reduce((sum, s) => sum + (s.points ?? 0), 0)
      expect(points).toBeCloseTo(split.delta!, 9)
      // ranked, so the list and the strip read top-down
      const shares = split.sessions.map((s) => s.share)
      expect([...shares].sort((a, b) => b - a)).toEqual(shares)
    }
  })
})
