// the parser, against the python oracle.
//
// `test/fixtures/requests-expected.jsonl` is `jobs/extract.py`'s own output over
// `test/fixtures/home`, regenerated by `scripts/refresh-oracle.sh`. the two must
// agree request by request, or the split is dividing a different number than the
// proof measured.
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { costOf, familyOf, priceFor } from './prices'
import { projectsRoot, scan, transcriptFiles } from './transcripts'

const FIXTURE_HOME = join(import.meta.dirname, '..', 'test', 'fixtures', 'home')
const EXPECTED = join(import.meta.dirname, '..', 'test', 'fixtures', 'requests-expected.jsonl')

interface Expected {
  t: number
  file: string
  mid: string
  sid: string
  agent: boolean
  model: string
  fam: string
  in: number
  cw1h: number
  cw5m: number
  cr: number
  out: number
  cost: number
  priced: boolean
}

/** the oracle was written from one checkout; key its paths on the fixture home so any checkout matches */
function fromHome(path: string): string {
  return path.slice(path.indexOf('/test/fixtures/home/'))
}

function oracle(): Expected[] {
  return readFileSync(EXPECTED, 'utf8')
    .split('\n')
    .filter(Boolean)
    .map((line) => JSON.parse(line) as Expected)
}

describe('prices', () => {
  it('takes the longest matching prefix', () => {
    expect(priceFor('claude-sonnet-4-5-20250929')).toEqual([3.0, 15.0])
    expect(priceFor('claude-opus-5')).toEqual([5.0, 25.0])
    expect(priceFor('<synthetic>')).toBeNull()
  })

  it('prices the cache buckets at their own multipliers', () => {
    // 1M cache-read opus tokens is a tenth of the 5.00 input price
    expect(costOf('claude-opus-5', { in: 0, cw1h: 0, cw5m: 0, cr: 1e6, out: 0 })).toBeCloseTo(0.5, 9)
    expect(costOf('claude-opus-5', { in: 0, cw1h: 1e6, cw5m: 0, cr: 0, out: 0 })).toBeCloseTo(10, 9)
    expect(costOf('claude-opus-5', { in: 0, cw1h: 0, cw5m: 1e6, cr: 0, out: 0 })).toBeCloseTo(6.25, 9)
    expect(costOf('claude-opus-5', { in: 0, cw1h: 0, cw5m: 0, cr: 0, out: 1e6 })).toBeCloseTo(25, 9)
  })

  it('reads the family out of the model id', () => {
    expect(familyOf('claude-fable-5-1')).toBe('fable')
    expect(familyOf('<synthetic>')).toBe('other')
  })
})

describe('scan, against jobs/extract.py', () => {
  it('finds the same files', () => {
    const files = transcriptFiles(projectsRoot(FIXTURE_HOME))
    expect(files.length).toBeGreaterThan(3)
    expect(files.filter((f) => f.agent).length).toBeGreaterThan(0)
  })

  it('produces the same request for the same (file, message id)', async () => {
    const expected = oracle()
    const { records } = await scan(0, 9_999_999_999, projectsRoot(FIXTURE_HOME))
    expect(records.length).toBe(expected.length)

    const mine = new Map(records.map((r) => [`${fromHome(r.file)} ${r.mid}`, r]))
    for (const row of expected) {
      const got = mine.get(`${fromHome(row.file)} ${row.mid}`)
      expect(got, `${row.file} ${row.mid}`).toBeDefined()
      expect(got!.t).toBe(row.t)
      expect(got!.model).toBe(row.model)
      expect(got!.family).toBe(row.fam)
      expect(got!.priced).toBe(row.priced)
      expect([got!.in, got!.cw1h, got!.cw5m, got!.cr, got!.out]).toEqual([row.in, row.cw1h, row.cw5m, row.cr, row.out])
      expect(got!.cost).toBeCloseTo(row.cost, 10)
    }
  })

  it('folds a subagent into its parent session, where extract.py kept the agent file name', async () => {
    const { records } = await scan(0, 9_999_999_999, projectsRoot(FIXTURE_HOME))
    const agents = records.filter((r) => r.agent && r.file.includes('/subagents/'))
    expect(agents.length).toBeGreaterThan(0)
    for (const record of agents) {
      // …/projects/<project>/<session id>/subagents/agent-x.jsonl
      const parent = record.file.split('/').at(-3)
      expect(record.sessionId).toBe(parent)
    }
  })

  it('keeps only the last line per message id', async () => {
    const { records } = await scan(0, 9_999_999_999, projectsRoot(FIXTURE_HOME))
    const keys = records.map((r) => `${r.file} ${r.mid}`)
    expect(new Set(keys).size).toBe(keys.length)
  })

  it('honours the window', async () => {
    const { records } = await scan(0, 9_999_999_999, projectsRoot(FIXTURE_HOME))
    const cut = records[Math.floor(records.length / 2)]!.t
    const { records: later } = await scan(cut, 9_999_999_999, projectsRoot(FIXTURE_HOME))
    expect(later.every((r) => r.t >= cut)).toBe(true)
    expect(later.length).toBeLessThan(records.length)
  })

  it('reads a title off the first user turn', async () => {
    const { sessions } = await scan(0, 9_999_999_999, projectsRoot(FIXTURE_HOME))
    const titles = [...sessions.values()].map((s) => s.title)
    expect(titles.filter(Boolean).length).toBeGreaterThan(0)
    expect(titles.every((t) => t === null || !t.startsWith('<'))).toBe(true)
  })
})
